In [7]:
# Render our plots inline
%matplotlib inline

import pandas as pd
import matplotlib.pyplot as plt
import sys
default_encoding = 'utf-8'
if sys.getdefaultencoding() != default_encoding:
    reload(sys)
    sys.setdefaultencoding(default_encoding)

pd.set_option('display.mpl_style', 'default') # Make the graphs a bit prettier
plt.rcParams['figure.figsize'] = (15, 5)

# 1.1 Reading data from a csv file

You can read data from a CSV file using the `read_csv` function. By default, it assumes that the fields are comma-separated.

We're going to be looking some cyclist data from Montréal. Here's the [original page](http://donnees.ville.montreal.qc.ca/dataset/velos-comptage) (in French), but it's already included in this repository. We're using the data from 2012.

This dataset is a list of how many people were on 7 different bike paths in Montreal, each day.

In [5]:
broken_df = pd.read_csv('C:\\pythoncoding\\pandas\\pandas-cookbook\\data\\bikes.csv')

In [9]:
# Look at the first 3 rows
broken_df

    Date;Berri 1;Br锟絙euf (donn锟絜s non disponibles);C锟絫e-Sainte-Catherine;Maisonneuve 1;Maisonneuve 2;du Parc;Pierre-Dupuy;Rachel1;St-Urbain (donn锟絜s non disponibles)
0                     01/01/2012;35;;0;38;51;26;10;16;
1                     02/01/2012;83;;1;68;153;53;6;43;
2                   03/01/2012;135;;2;104;248;89;3;58;
3                  04/01/2012;144;;1;116;318;111;8;61;
4                  05/01/2012;197;;2;124;330;97;13;95;
5                    06/01/2012;146;;0;98;244;86;4;75;
6                     07/01/2012;98;;2;80;108;53;6;54;
7                     08/01/2012;95;;1;62;98;64;11;63;
8                09/01/2012;244;;2;165;432;198;12;173;
9                10/01/2012;397;;3;238;563;275;18;241;
10               11/01/2012;273;;0;182;443;258;12;194;
11                 12/01/2012;157;;1;134;261;137;9;63;
12                     13/01/2012;75;;0;41;105;64;2;0;
13                      14/01/2012;32;;0;54;56;19;0;1;
14                      15/01/2012;54;;0;33;60;18;0;0;
15                   16/01/2012;168;;2;136;312;137;1;0
16                     17/01/2012;155;;0;86;256;74;0;0
17                     18/01/2012;139;;0;66;188;68;3;0
18                    19/01/2012;191;;1;104;248;79;3;0
19                     20/01/2012;161;;4;96;217;67;1;1
20                       21/01/2012;53;;0;47;70;32;1;0
21                       22/01/2012;71;;0;41;73;35;5;0
22                    23/01/2012;210;;6;114;357;91;6;0
23                   24/01/2012;299;;1;189;444;174;4;0
24                   25/01/2012;334;;1;217;453;180;4;0
25                   26/01/2012;306;;0;215;495;191;0;1
26                      27/01/2012;91;;5;79;204;65;0;0
27                      28/01/2012;80;;1;61;123;33;9;1
28                      29/01/2012;87;;1;65;132;40;7;0
29                   30/01/2012;219;;0;146;371;152;2;0
..                                                 ...
280         07/10/2012;1580;;660;922;1629;860;695;2052
281       08/10/2012;1854;;880;987;1818;1040;1115;2502
282      09/10/2012;4787;;2210;3026;5138;3418;927;4078
283      10/10/2012;3115;;1537;2081;3681;2608;560;2703
284      11/10/2012;3746;;1857;2569;4694;3034;558;3457
285      12/10/2012;3169;;1460;2261;4045;2564;448;3224
286       13/10/2012;1783;;802;1205;2113;1183;681;2309
287             14/10/2012;587;;287;443;852;503;65;952
288      15/10/2012;3292;;1678;2165;4197;2754;560;3183
289      16/10/2012;3739;;1858;2684;4681;2997;554;3593
290      17/10/2012;4098;;1964;2645;4836;3063;728;3834
291     18/10/2012;4671;;2292;3129;5542;3477;1108;4245
292        19/10/2012;1313;;597;885;1668;1209;111;1486
293       20/10/2012;2011;;748;1323;2266;1213;797;2243
294         21/10/2012;1277;;609;869;1777;898;242;1648
295      22/10/2012;3650;;1819;2495;4800;3023;757;3721
296      23/10/2012;4177;;1997;2795;5216;3233;795;3554
297      24/10/2012;3744;;1868;2625;4900;3035;649;3622
298      25/10/2012;3735;;1815;2528;5010;3017;631;3767
299     26/10/2012;4290;;1987;2754;5246;3000;1456;4578
300       27/10/2012;1857;;792;1244;2461;1193;618;2471
301         28/10/2012;1310;;697;910;1776;955;387;1876
302      29/10/2012;2919;;1458;2071;3768;2440;411;2795
303      30/10/2012;2887;;1251;2007;3516;2255;338;2790
304      31/10/2012;2634;;1294;1835;3453;2220;245;2570
305      01/11/2012;2405;;1208;1701;3082;2076;165;2461
306        02/11/2012;1582;;737;1109;2277;1392;97;1888
307          03/11/2012;844;;380;612;1137;713;105;1302
308          04/11/2012;966;;446;710;1277;692;197;1374
309      05/11/2012;2247;;1170;1705;3221;2143;179;2430

[310 rows x 1 columns]

You'll notice that this is totally broken! `read_csv` has a bunch of options that will let us fix that, though. Here we'll

* change the column separator to a `;`
* Set the encoding to `'latin1'` (the default is `'utf8'`)
* Parse the dates in the 'Date' column
* Tell it that our dates have the day first instead of the month first
* Set the index to be the 'Date' column

In [10]:
fixed_df = pd.read_csv('C:\\pythoncoding\\pandas\\pandas-cookbook\\data\\bikes.csv', sep=';', encoding='latin1', parse_dates=['Date'], dayfirst=True, index_col='Date')
fixed_df[:3]

,Berri 1,Brébeuf (données non disponibles),Côte-Sainte-Catherine,Maisonneuve 1,Maisonneuve 2,du Parc,Pierre-Dupuy,Rachel1,St-Urbain (données non disponibles)
Date,,,,,,,,,
2012-01-01,35,NaN,0,38,51,26,10,16,NaN
2012-01-02,83,NaN,1,68,153,53,6,43,NaN
2012-01-03,135,NaN,2,104,248,89,3,58,NaN

# 1.2 Selecting a column

When you read a CSV, you get a kind of object called a `DataFrame`, which is made up of rows and columns. You get columns out of a DataFrame the same way you get elements out of a dictionary.

Here's an example:

In [ ]:
fixed_df['Berri 1']

# 1.3 Plotting a column

Just add `.plot()` to the end! How could it be easier? =)

We can see that, unsurprisingly, not many people are biking in January, February, and March,

In [ ]:
fixed_df['Berri 1'].plot()

We can also plot all the columns just as easily. We'll make it a little bigger, too.
You can see that it's more squished together, but all the bike paths behave basically the same -- if it's a bad day for cyclists, it's a bad day everywhere.

In [ ]:
fixed_df.plot(figsize=(15, 10))

# 1.4 Putting all that together

Here's the code we needed to write do draw that graph, all together:

In [13]:
df = pd.read_csv('C:\\pythoncoding\\pandas\\pandas-cookbook\\data\\bikes.csv', sep=';', encoding='latin1', parse_dates=['Date'], dayfirst=True, index_col='Date')
#df['Berri 1'].plot()
df.head()

,Berri 1,Brébeuf (données non disponibles),Côte-Sainte-Catherine,Maisonneuve 1,Maisonneuve 2,du Parc,Pierre-Dupuy,Rachel1,St-Urbain (données non disponibles)
Date,,,,,,,,,
2012-01-01,35,NaN,0,38,51,26,10,16,NaN
2012-01-02,83,NaN,1,68,153,53,6,43,NaN
2012-01-03,135,NaN,2,104,248,89,3,58,NaN
2012-01-04,144,NaN,1,116,318,111,8,61,NaN
2012-01-05,197,NaN,2,124,330,97,13,95,NaN

<style>
    @font-face {
        font-family: "Computer Modern";
        src: url('http://mirrors.ctan.org/fonts/cm-unicode/fonts/otf/cmunss.otf');
    }
    div.cell{
        width:800px;
        margin-left:16% !important;
        margin-right:auto;
    }
    h1 {
        font-family: Helvetica, serif;
    }
    h4{
        margin-top:12px;
        margin-bottom: 3px;
       }
    div.text_cell_render{
        font-family: Computer Modern, "Helvetica Neue", Arial, Helvetica, Geneva, sans-serif;
        line-height: 145%;
        font-size: 130%;
        width:800px;
        margin-left:auto;
        margin-right:auto;
    }
    .CodeMirror{
            font-family: "Source Code Pro", source-code-pro,Consolas, monospace;
    }
    .text_cell_render h5 {
        font-weight: 300;
        font-size: 22pt;
        color: #4057A1;
        font-style: italic;
        margin-bottom: .5em;
        margin-top: 0.5em;
        display: block;
    }
    
    .warning{
        color: rgb( 240, 20, 20 )
        }